"""Unit tests for the bug report tool (ha_report_issue)."""

from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from ha_mcp import __version__
from ha_mcp.tools.tools_bug_report import register_bug_report_tools


class TestBugReportTool:
    """Test suite for the ha_report_issue tool."""

    @pytest.fixture
    def mock_mcp(self):
        """Create a mock MCP server."""
        mcp = MagicMock()
        # Store registered tools so we can call them in tests
        mcp._tools = {}

        def tool_decorator(*args, **kwargs):
            def wrapper(func):
                mcp._tools[func.__name__] = func
                return func

            return wrapper

        mcp.tool = tool_decorator
        return mcp

    @pytest.fixture
    def mock_client(self):
        """Create a mock Home Assistant client."""
        client = MagicMock()
        client.get_config = AsyncMock()
        client.get_states = AsyncMock()
        return client

    @pytest.fixture
    def registered_tools(self, mock_mcp, mock_client):
        """Register the bug report tools and return the mock MCP."""
        register_bug_report_tools(mock_mcp, mock_client)
        return mock_mcp

    @pytest.fixture
    def ha_report_issue_func(self, registered_tools):
        """Return the unwrapped ha_report_issue function."""
        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__
        return actual_func

    @pytest.mark.asyncio
    async def test_bug_report_success(self, registered_tools, mock_client):
        """Test successful bug report generation."""
        # Setup mock responses
        mock_client.get_config.return_value = {
            "version": "2024.12.0",
            "location_name": "Test Home",
            "time_zone": "America/New_York",
        }
        mock_client.get_states.return_value = [
            {"entity_id": f"light.light_{i}"} for i in range(150)
        ]

        # Get the registered tool (now called ha_report_issue)
        ha_report_issue = registered_tools._tools["ha_report_issue"]

        # Strip the decorator wrapper to get the actual function
        # The log_tool_usage decorator wraps the function
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        # Call the tool with default parameters
        result = await actual_func()

        # Verify the result
        assert result["success"] is True
        assert "diagnostic_info" in result
        assert "formatted_report" in result
        assert "runtime_bug_template" in result
        assert "agent_behavior_template" in result
        assert "anonymization_guide" in result
        assert "recent_logs" in result
        assert "log_count" in result
        assert "instructions" in result
        assert "suggested_title" in result
        assert "duplicate_check_urls" in result

        # Check diagnostic info
        diag = result["diagnostic_info"]
        assert diag["ha_mcp_version"] == __version__
        assert diag["home_assistant_version"] == "2024.12.0"
        assert diag["connection_status"] == "Connected"
        assert diag["entity_count"] == 150
        assert diag["location_name"] == "Test Home"
        assert diag["time_zone"] == "America/New_York"

        # Check formatted report contains expected content
        report = result["formatted_report"]
        assert "=== ha-mcp Bug Report Info ===" in report
        assert "Home Assistant Version: 2024.12.0" in report
        assert f"ha-mcp Version: {__version__}" in report
        assert "Connection Status: Connected" in report
        assert "Entity Count: 150" in report

        # Check runtime bug template
        runtime_template = result["runtime_bug_template"]
        assert "## 🚨 Auto-Generated by `ha_report_issue` Tool" in runtime_template
        assert "📋 Bug Description" in runtime_template
        assert "🔄 Steps to Reproduce" in runtime_template
        assert "✅ Expected vs ❌ Actual Behavior" in runtime_template
        assert "🔧 Environment" in runtime_template
        assert "https://github.com/homeassistant-ai/ha-mcp/issues/new?template=runtime_bug.yml" in runtime_template

        # Check agent behavior template
        agent_template = result["agent_behavior_template"]
        assert "## 🤖 Auto-Generated by `ha_report_issue` Tool" in agent_template
        assert "🤖 What Did the AI Agent Do?" in agent_template
        assert "🎯 What Should the Agent Have Done?" in agent_template
        assert "🔧 Tool Calls Made" in agent_template
        assert "https://github.com/homeassistant-ai/ha-mcp/issues/new?template=agent_behavior.yml" in agent_template

        # Check anonymization guide
        anon_guide = result["anonymization_guide"]
        assert "## Anonymization Guide" in anon_guide
        assert "MUST ANONYMIZE" in anon_guide
        assert "CONSIDER ANONYMIZING" in anon_guide
        assert "KEEP AS-IS" in anon_guide

    @pytest.mark.asyncio
    async def test_bug_report_connection_error(self, registered_tools, mock_client):
        """Test bug report when connection fails."""
        # Setup mock to raise exception
        mock_client.get_config.side_effect = Exception("Connection refused")
        mock_client.get_states.side_effect = Exception("Connection refused")

        # Get the registered tool
        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        # Call the tool
        result = await actual_func()

        # Should still succeed but with error info
        assert result["success"] is True
        diag = result["diagnostic_info"]
        assert diag["ha_mcp_version"] == __version__
        assert "Connection Error" in diag["connection_status"]
        assert diag["home_assistant_version"] == "Unknown"
        assert diag["entity_count"] == 0

    @pytest.mark.asyncio
    async def test_bug_report_partial_failure(self, registered_tools, mock_client):
        """Test bug report when only some data is available."""
        # Config succeeds but states fails
        mock_client.get_config.return_value = {
            "version": "2024.12.0",
            "location_name": "Test Home",
        }
        mock_client.get_states.side_effect = Exception("States unavailable")

        # Get the registered tool
        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        # Call the tool
        result = await actual_func()

        # Should succeed with partial info
        assert result["success"] is True
        diag = result["diagnostic_info"]
        assert diag["connection_status"] == "Connected"
        assert diag["home_assistant_version"] == "2024.12.0"
        assert diag["entity_count"] == 0  # Failed to get states

    @pytest.mark.asyncio
    async def test_bug_report_issue_urls(self, registered_tools, mock_client):
        """Test that both template URLs are correctly included."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        result = await actual_func()

        # Check both templates have correct URLs
        assert "https://github.com/homeassistant-ai/ha-mcp/issues/new?template=runtime_bug.yml" in result["runtime_bug_template"]
        assert "https://github.com/homeassistant-ai/ha-mcp/issues/new?template=agent_behavior.yml" in result["agent_behavior_template"]

    @pytest.mark.asyncio
    async def test_bug_report_no_timezone(self, registered_tools, mock_client):
        """Test bug report when timezone is not available."""
        mock_client.get_config.return_value = {
            "version": "2024.12.0",
            # No time_zone key
        }
        mock_client.get_states.return_value = []

        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        result = await actual_func()

        # Should still have time_zone with Unknown value
        assert result["success"] is True
        assert result["diagnostic_info"]["time_zone"] == "Unknown"

    @pytest.mark.asyncio
    async def test_bug_report_with_custom_tool_call_count(
        self, registered_tools, mock_client
    ):
        """Test bug report with custom tool_call_count parameter."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        # Mock get_recent_logs to verify it's called with correct max_entries
        # Formula: AVG_LOG_ENTRIES_PER_TOOL (3) * 2 * tool_call_count
        with patch(
            "ha_mcp.tools.tools_bug_report.get_recent_logs"
        ) as mock_get_logs:
            mock_get_logs.return_value = [
                {
                    "timestamp": "2024-12-01T10:00:00",
                    "tool_name": "ha_search_entities",
                    "success": True,
                    "execution_time_ms": 150,
                },
                {
                    "timestamp": "2024-12-01T10:00:01",
                    "tool_name": "ha_call_service",
                    "success": False,
                    "execution_time_ms": 50,
                    "error_message": "Service not found",
                },
            ]

            # Call with tool_call_count=5
            result = await actual_func(tool_call_count=5)

            # Verify get_recent_logs was called with 3 * 4 * 5 = 60 (multiplier changed from 2x to 4x)
            mock_get_logs.assert_called_once_with(max_entries=60)

            # Verify logs are included in result
            assert result["log_count"] == 2
            assert len(result["recent_logs"]) == 2

    @pytest.mark.asyncio
    async def test_bug_report_log_formatting(self, registered_tools, mock_client):
        """Test that logs are properly formatted in the report."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        with patch(
            "ha_mcp.tools.tools_bug_report.get_recent_logs"
        ) as mock_get_logs:
            mock_get_logs.return_value = [
                {
                    "timestamp": "2024-12-01T10:00:00.123456",
                    "tool_name": "ha_get_state",
                    "success": True,
                    "execution_time_ms": 100,
                },
                {
                    "timestamp": "2024-12-01T10:00:01.654321",
                    "tool_name": "ha_call_service",
                    "success": False,
                    "execution_time_ms": 50,
                    "error_message": "Entity not found",
                },
            ]

            result = await actual_func()

            # Check formatted_report includes log section
            report = result["formatted_report"]
            assert "=== Recent Tool Calls (2 entries) ===" in report
            assert "ha_get_state" in report
            assert "ha_call_service" in report
            assert "OK" in report
            assert "FAIL" in report

            # Check template includes logs
            template = result["runtime_bug_template"]
            assert "📊 Recent Tool Calls" in template
            assert "ha_get_state" in template

    @pytest.mark.asyncio
    async def test_bug_report_instructions(self, registered_tools, mock_client):
        """Test that instructions for the AI agent are included."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        ha_report_issue = registered_tools._tools["ha_report_issue"]
        actual_func = ha_report_issue
        while hasattr(actual_func, "__wrapped__"):
            actual_func = actual_func.__wrapped__

        result = await actual_func()

        # Check instructions are present and useful
        instructions = result["instructions"]
        assert "RUNTIME_BUG_TEMPLATE" in instructions
        assert "AGENT_BEHAVIOR_TEMPLATE" in instructions
        assert "ANALYZE THE CONVERSATION" in instructions
        assert "anonymize" in instructions.lower()
        assert "personal information" in instructions.lower()

    @pytest.mark.asyncio
    async def test_bug_report_suggested_title(self, ha_report_issue_func, mock_client):
        """Test that a suggested title is generated."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        with patch(
            "ha_mcp.tools.tools_bug_report.get_recent_logs"
        ) as mock_get_logs:
            mock_get_logs.return_value = [
                {
                    "timestamp": "2024-12-01T10:00:00",
                    "tool_name": "ha_call_service",
                    "success": False,
                    "execution_time_ms": 50,
                    "error_message": "Service not found",
                },
            ]

            result = await ha_report_issue_func()

            # Check suggested title is present and has correct format
            assert "suggested_title" in result
            title = result["suggested_title"]
            assert isinstance(title, str)
            assert len(title) > 0
            assert len(title) <= 60
            # Should be exactly: "tool_name: error_message"
            assert title == "ha_call_service: Service not found"

    @pytest.mark.asyncio
    async def test_bug_report_suggested_title_no_errors(
        self, ha_report_issue_func, mock_client
    ):
        """Test title generation when there are no errors."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        with patch(
            "ha_mcp.tools.tools_bug_report.get_recent_logs"
        ) as mock_get_logs:
            mock_get_logs.return_value = [
                {
                    "timestamp": "2024-12-01T10:00:00",
                    "tool_name": "ha_get_state",
                    "success": True,
                    "execution_time_ms": 100,
                },
            ]

            result = await ha_report_issue_func()

            # Should still generate a generic title
            assert "suggested_title" in result
            title = result["suggested_title"]
            assert isinstance(title, str)
            assert len(title) > 0
            assert len(title) <= 60

    @pytest.mark.asyncio
    async def test_bug_report_duplicate_check_urls(self, ha_report_issue_func, mock_client):
        """Test that duplicate check URLs are generated with correct keywords."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        with patch(
            "ha_mcp.tools.tools_bug_report.get_recent_logs"
        ) as mock_get_logs:
            mock_get_logs.return_value = [
                {
                    "timestamp": "2024-12-01T10:00:00",
                    "tool_name": "ha_call_service",
                    "success": False,
                    "execution_time_ms": 50,
                    "error_message": "Connection timeout",
                },
            ]

            result = await ha_report_issue_func()

            # Check duplicate check URLs are present
            assert "duplicate_check_urls" in result
            urls = result["duplicate_check_urls"]
            assert isinstance(urls, list)
            assert len(urls) > 0
            # All URLs should be GitHub issue search URLs
            for url in urls:
                assert "github.com/homeassistant-ai/ha-mcp/issues" in url
                assert "is%3Aissue" in url

            # Verify keywords are in URLs
            url_content = "".join(urls)
            assert "ha_call_service" in url_content
            assert "connection" in url_content
            assert "timeout" in url_content

    @pytest.mark.asyncio
    async def test_bug_report_updated_instructions(
        self, ha_report_issue_func, mock_client
    ):
        """Test that instructions include new workflow steps."""
        mock_client.get_config.return_value = {"version": "2024.12.0"}
        mock_client.get_states.return_value = []

        result = await ha_report_issue_func()

        instructions = result["instructions"]
        # Check for new workflow steps
        assert "Check for duplicates FIRST" in instructions
        assert "duplicate_check_urls" in instructions
        assert "suggested_title" in instructions
        assert "markdown code block" in instructions.lower()
        assert "```markdown" in instructions
        assert "PROMINENTLY display the submission URL" in instructions
